version: '3.4'

services:
  dynamicwebappcore:
    container_name: 'dynamicwebappcore'
    image: 'dynamicwebappcore'
    build:
      context: .
      dockerfile: DynamicWebAppCore/Dockerfile
    ports:
     - "5000:5000"
    depends_on:
     - "openweathermapapi"
    networks:
      - weatherapp-network


  openweathermapapi:
    container_name: 'openweathermapapi'
    image: 'openweathermapapi'
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
     - "6000:6000" 
    networks:
      - weatherapp-network

networks:
  weatherapp-network:
    driver: bridge
  