version: '3.4'

services:
    
  omreactcoreapp:
    image: 'omreactcoreapp'
    build:
      context: .
      dockerfile: OmReactCoreApp/Dockerfile
    ports:
     - 8080:80
     - 8001:443
    depends_on:
     - "openweathermapapi"
    

  openweathermapapi:
    
    image: 'openweathermapapi'
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
     - 8081:80
    


  